### ISSUE TITLE
Usage Example for nginx

### ISSUE THREAD

**Issue by mritzmann** [DigitaleGesellschaft/Anonip#1]
Is there also a [Usage Example](https://github.com/DigitaleGesellschaft/Anonip#usage) for nginx?

**Comment by ganti** [comment]
Markus, this is a very good question, since all webservers should have the possibility of anonymous logging. So out of interest I had to investigate into first. There are multiple ways, you could use external plugins then use syslog and pipe it through AnonIP.  

What you can use to achieve the same as with AnonIP is the built in functionality of nginx, to me the best way to do it, though I didn't test it.
https://gist.github.com/fluential/e2b4ceea628ead5162f0 

A good startingpoint to understand logs in nginx monitoring in gerneral is this page: https://www.nginx.com/resources/admin-guide/logging-and-monitoring/

**Comment by htgoebel** [comment]
nginx also supports writing both access and error log to a socket in syslog format, see https://nginx.org/en/docs/syslog.html. So it should be easy write a simple syslog receiver (base on e.g https://gist.github.com/marcelom/4218010/) to process the log entries. (Indeed I already did as a proof of concept.) 

The only draw back is that one would either need to start one receiver per log-file or somehow separate whereto each of the log entries should go. This will be esp. messy when using virtual hosts.

**Comment by open-dynaMIX** [comment]
@htgoebel Nice! It would be great to have some documentation in the README about the usage of anonip with nginx.

Another approach would be to let nginx write it's logs to a FIFO and then let anonip read from that FIFO. This should be possible without additional code. I haven't tested this though.
