### ISSUE TITLE
Could it be made work with ErrorLog too?

### ISSUE THREAD

**Issue by herrernst** [DigitaleGesellschaft/Anonip#2]
I tried it also with ErrorLog, but it doesn't replace the IP address in format like that line:
`[Wed Jun 27 20:37:49.123456 2018] [cgi:error] [pid 1234] [client 222.111.222.111:12345] script not found or unable to stat: /var/www/cgi-bin/test.php5`
Would be nice if it could work here too. Thanks.

**Comment by ganti** [comment]
Hallo Herr Ernst

The problem was the port number, I added a small fix to the script see here: https://github.com/DigitaleGesellschaft/Anonip/blob/port_fix_test/anonip.py

I annoned your error log with the param `--column 10`
this code will be overseen by a second person and then integrated into the master branch.

Best
Simon

**Comment by herrernst** [comment]
Wow, what a fast fix, thank you! Only one cosmetic thing: the closing `]` now is gone:
`[client 62.178.32.0 script not found or`...
